ecomfe/veui

- CHANGELOG.md
- packages/veui/demo/cases/Select.vue
- packages/veui/src/components/Select/Option.vue
- packages/veui/src/components/Select/Select.vue
本次修改如下：
1. 修改select/Option的props#value的要求，可以使任何值
2. 更新select/Option成两个slot. slot[name=default]和slot[name=label]
对这demo对比了一下，正常来说并无影响
> 修改Option的value prop限制；增加slot与slot[name=label]

- packages/veui/src/managers/overlay.js
直接遍历 parentNode 的 children 的时候，判断的是未初始化的 prevNode，这个逻辑永远是设置不了 parentNode 的一级 child 的zIndex
> bugfix: init prevNode with parentNode

- packages/veui-theme-one/components/tabs.less
- packages/veui/demo/cases/Tabs.vue
- packages/veui/src/components/Tabs/Tab.vue
- packages/veui/src/components/Tabs/Tabs.vue
- packages/veui/src/directives/resize.js
> 为 Tabs 增加 WAI-ARIA 支持

- packages/veui-theme-one/common.less
- packages/veui-theme-one/components/calendar.less
- packages/veui-theme-one/components/date-picker.less
- packages/veui-theme-one/mixins.less
- packages/veui/src/components/Calendar.vue
- packages/veui/src/components/DatePicker.vue
- packages/veui/src/managers/focus.js
- packages/veui/src/utils/dom.js
* add `.veui-sr-only`
* fix backward tabbing by adding focus ward on both directions
* add aria support for DatePicker
#234.
> 为 DatePicker 增加键盘操作

- packages/veui-theme-one/components/Progress.js
- packages/veui/src/components/Icon.vue
- packages/veui/src/components/Pagination.vue
- packages/veui/src/components/Progress.vue
- packages/veui/src/components/Searchbox.vue
- packages/veui/src/components/Select/Option.vue
- packages/veui/src/components/Uploader.vue
- packages/veui/src/mixins/ui.js
在主题的 JS 文件中提供无法通过 CSS 定义的样式逻辑。
目前的逻辑是这样的：
```js
{
icons: {
success: 'check'
},
ui: {
size: {
values: ['tiny'],
data: {
default: {
radius: 60
},
tiny: {
radius: 13
}
}
}
}
}
```
组件代码中按如下方式调用：
```js
this.uiData.radius // 60 for `default`, 13 for `tiny`
```
这样就不需要在组件中感知主题提供哪些 `ui` 可选值了。当然，在组件逻辑中还是要提供默认值的，因为这些配置对于主题来说是可选的。
这个 PR 还有一些代码风格调整。
> 去除 `Progress` 组件对 `ui` 值的依赖

- packages/veui-theme-one/components/carousel.less
- packages/veui/demo/cases/Carousel.vue
- packages/veui/src/components/Carousel.vue
- packages/veui/src/components/Radio.vue
- packages/veui/src/components/RadioGroup.vue
> Add ARIA support for Carousel

- packages/veui/src/directives/outside.js
> 修复outside delay模式未清除定时器

- packages/veui/src/components/Calendar.vue
- packages/veui/src/components/DatePicker.vue
- packages/veui/src/components/Dropdown.vue
- packages/veui/src/components/Radio.vue
- packages/veui/src/components/Select/Option.vue
- packages/veui/src/components/Select/OptionGroup.vue
- packages/veui/src/components/Select/Select.vue
> 为 Select/Dropdown 等组件添加 ARIA 支持

- CHANGELOG.md
- packages/veui/src/components/Progress.vue
> 为 Progress 组件添加 ARIA 支持

- packages/veui/src/managers/focus.js
尝试下这个逻辑：
关闭浮层自动恢复 focus 状态时，如果最近一次交互非 pointer event 触发，就不恢复。
> 根据最近交互事件决定 focus 恢复的行为

- packages/veui-theme-one/components/searchbox.less
修正全局搜索框的展示与 UE 设计不符的地方。
1. 在可交互的情况系下，按钮是覆盖『input 边缘线』的。
> fix Searchbox style

- packages/veui/demo/cases/Alert.vue
- packages/veui/demo/cases/Dialog.vue
1. demo alert页面 dialog 不能关闭。
2. dialog 页面进入后计时器被创建，路由切换原有计时器不会销毁，数量会增长。
3. dialog 页面open toast 被点击后，提示信息会一直刷屏并且关不掉。原因：计时器未被销毁。
4. 解决上述3问题，顺便增加了toast演示例子（参考AlertBox)。
> 修复dialog[确定/取消]按钮点击后无法关闭dialog 问题。

- packages/veui-theme-one/components/region-picker.less
- packages/veui/src/components/Carousel.vue
- packages/veui/src/components/Checkbox.vue
- packages/veui/src/components/Radio.vue
- packages/veui/src/components/RegionPicker.vue
- packages/veui/src/components/Textarea.vue
- packages/veui/src/directives/outside.js
- packages/veui/src/managers/focus.js
- packages/veui/src/utils/dom.js
- packages/veui/src/utils/math.js
#234.
* keyboard nav & WAI-ARIA support for `RegionPicker`
* `log10` in `utils/math`
* `focusBefore` & `focusAfter` in `utils/dom`
* `focus({ visible })` for `Radio` & `Checkbox`
> 为 RegionPicker 添加键盘导航 & WAI-ARIA 支持

- CHANGELOG.md
- packages/veui/src/components/Checkbox.vue
- packages/veui/src/components/Input.vue
- packages/veui/src/components/Label.vue
- packages/veui/src/components/NumberInput.vue
- packages/veui/src/components/Radio.vue
- packages/veui/src/components/Searchbox.vue
- packages/veui/src/components/Switch.vue
- packages/veui/src/components/Textarea.vue
- packages/veui/src/mixins/dropdown.js
Should look for the first component with `uiType` value `input` among all descendants of the closest `field` instead of only searching first child component of each level.
> Fix input component lookup in Label

- CHANGELOG.md
- package-lock.json
- package.json
- packages/babel-plugin-veui/package-lock.json
- packages/babel-preset-veui/package-lock.json
- packages/veui-loader/package-lock.json
- packages/veui-theme-one/build/svg2json.js
- packages/veui-theme-one/components/textarea.less
- packages/veui-theme-one/package-lock.json
- packages/veui/demo/cases/Uploader.vue
- packages/veui/package-lock.json
- packages/veui/package.json
- packages/veui/src/components/AlertBox.vue
- packages/veui/src/components/Breadcrumb.vue
- packages/veui/src/components/BreadcrumbItem.vue
- packages/veui/src/components/Calendar.vue
- packages/veui/src/components/Checkbox.vue
- packages/veui/src/components/ConfirmBox.vue
- packages/veui/src/components/Dialog.vue
- packages/veui/src/components/Icon.vue
- packages/veui/src/components/Progress.vue
- packages/veui/src/components/Radio.vue
- packages/veui/src/components/Sorter.vue
- packages/veui/src/components/Textarea.vue
- packages/veui/src/directives/resize.js
- packages/veui/src/managers/config.js
- packages/veui/src/mixins/ui.js
- packages/veui/src/utils/helper.js
* `ui`
- 支持 `uiParts`，用来给主题指定每个组件的某些特定子组件的 `ui`。目前仅为 `Dialog` 添加了支持。
- 支持 `boolean` 类型的 `uiProp`。
* 升级 `vue-awesome` 的版本号
* 修复 `Calendar` 一些选择过程中预览用的范围起止判断
* 用 `lodash` 的 `keys` 代替 `Object.keys`
> 1.0.0-alpha.18

- packages/veui-loader/src/index.js
- packages/veui-theme-one/veui-loader-options.js
- packages/veui/build/webpack.base.conf.js
- packages/veui/test/veui-jest.js
* Move `veui-loader-options.js` into `veui-theme-one`
* Make `$` prefix in placeholder optional
> Minor tweak to loader

- CHANGELOG.md
- packages/veui-theme-one/components/Table.js
- packages/veui-theme-one/components/table.less
- packages/veui/demo/cases/Table.vue
- packages/veui/src/components/Table/Column.vue
- packages/veui/src/components/Table/Table.vue
- packages/veui/src/components/Table/_ColGroup.js
- packages/veui/src/components/Table/_TableBody.js
- packages/veui/src/components/Table/_TableFoot.js
- packages/veui/src/components/Table/_TableHead.js
- packages/veui/src/components/Table/_TableRow.js
- packages/veui/src/locale/en-US/Table.js
- packages/veui/src/locale/zh-Hans/Table.js
- packages/veui/src/utils/browser.js
- packages/veui/src/utils/helper.js
> （这个 PR 直接 rebase 了 #383）
使用方法：
* `Table` 增加 `expandable` prop，为 `true` 则支持行展开
* 展开行默认与主行的列配置一致（使用 `Column` 组件配置），采用 `data` 项中 `children` 数组座位对应行的数据源
* `Column` 增加了 scoped slot `sub-row`，支持为展开行定制内容格式
* `Table` 也增加了 scoped slot `sub-row`，用来展示打通所有列的展开行，此时覆盖 `Column` 中的配置
> Expandable row support for Table

- CHANGELOG.md
- packages/veui/demo/cases/Tabs.vue
- packages/veui/src/components/Tabs/Tab.vue
- packages/veui/src/components/Tabs/Tabs.vue
- packages/veui/src/components/Uploader.vue
增加 `matches` 函数 prop，用来判断当前 `Tab` 是否为激活状态，不再需要手动控制 `index`。
默认逻辑与现在的逻辑兼容：
```js
function matches (current, to) {
return current.fullPath === to.fullPath
}
```
其中 `current` 和 `to` 均为 Vue Router 的 [Route 对象](https://router.vuejs.org/api/#route-object-properties)。
> feat: add `matches` for `Tabs` & `Tab`

- packages/veui-theme-one-icons/package.json
- packages/veui-theme-one/package.json
- packages/veui/src/components/Calendar.vue
- packages/veui/src/components/CheckButtonGroup.vue
- packages/veui/src/components/CheckboxGroup.vue
- packages/veui/src/components/DatePicker.vue
- packages/veui/src/components/Input.vue
- packages/veui/src/components/NumberInput.vue
- packages/veui/src/components/Radio.vue
- packages/veui/src/components/RadioButtonGroup.vue
- packages/veui/src/components/RadioGroup.vue
- packages/veui/src/components/RegionPicker.vue
- packages/veui/src/components/Schedule.vue
- packages/veui/src/components/Searchbox.vue
- packages/veui/src/components/Slider.vue
- packages/veui/src/components/Switch.vue
- packages/veui/src/components/Textarea.vue
- packages/veui/src/components/Uploader.vue
- packages/veui/src/mixins/input.js
Move mixin `focusable` into `input` for input components.
> refactor: make inputs focusable

- packages/veui/demo/cases/Calendar.vue
- packages/veui/demo/cases/DatePicker.vue
- packages/veui/src/components/Calendar.vue
- packages/veui/src/components/DatePicker.vue
- packages/veui/src/locale/en-US/DatePicker.js
- packages/veui/src/locale/zh-Hans/DatePicker.js
Add prop: `type: 'date' | 'month' | 'year'`. The type of `selected` keeps as-is (native `Date`s). Users have to call `.getMonth()` and `.getFullYear()` to get the actual selectde month and/or year.
Setting `type` value other than `'date'` would make `range` and `multiple` to be ignored.
> feat: implement `type` prop for Calendar/DatePicker

- CHANGELOG.md
- packages/veui/demo/cases/Checkbox.vue
- packages/veui/demo/cases/Radio.vue
- packages/veui/jest.config.js
- packages/veui/src/components/Checkbox.vue
- packages/veui/src/components/Radio.vue
- packages/veui/src/components/Switch.vue
- packages/veui/test/unit/specs/components/Switch.spec.js
This PR removes `.sync` support for `Checkbox`'s `indeterminate` prop, it's now always decided by the parent component.
> fix: remove .sync support for Checkbox's indeterminate prop

- CHANGELOG.md
- packages/veui/demo/Console.vue
- packages/veui/demo/cases/Input.vue
- packages/veui/demo/cases/NumberInput.vue
- packages/veui/demo/cases/Textarea.vue
- packages/veui/src/components/Input.vue
- packages/veui/src/components/NumberInput.vue
- packages/veui/src/components/Textarea.vue
- packages/veui/test/unit/specs/components/Input.spec.js
- packages/veui/test/unit/specs/components/NumberInput.spec.js
- packages/veui/test/unit/specs/components/Textarea.spec.js
* Remove unnecessary props
* Use `inheritAttrs: false`
* Transparently pass down props/attrs to the native `<input>` elements
> Refine props/attrs fall-though behavior for Input/NumberInput/Textarea

- packages/babel-plugin-veui/src/index.js
fixes #467
`path.skip()` skips traversing the children of the current path.
`path.stop()` stops traversal entirely.
So by using `stop()`, it may stop the execution of other babel plugins on
this file. In this case, it's `proposal-decorators` that failed to run.
> fix: replace `stop()` with `skip()` so that other plugins won't break

- packages/veui/src/components/Schedule.vue
- packages/veui/src/directives/outside.js
- packages/veui/test/unit/specs/components/Schedule.spec.js
fix:
1.  设定disabled-hour后，勾选左侧的checkbox，仍会选中当天所有时刻，包括disabled-hour
2. 设定disabled为true后，左侧的checkbox和shortcuts仍可选择
3. 设定readonly为true后，Schedule仍能选择
4. tooltip slot中绑定的from值应为hour.start
5. demo/cases/schedule 页面，鼠标在页面上移动，会报“Uncaught TypeError: Cannot read property 'forEach' of undefined at getElementsByRefs (outside.js?2b20:58) ”的错误
> test: add test case for Schedule

- package-lock.json
- packages/babel-plugin-veui/package-lock.json
- packages/babel-preset-veui/package-lock.json
- packages/veui-loader/package-lock.json
- packages/veui-theme-dls-icons/package-lock.json
- packages/veui-theme-dls/components/region-picker.less
- packages/veui-theme-dls/components/tooltip.less
- packages/veui-theme-dls/dropdown.less
- packages/veui-theme-dls/package-lock.json
- packages/veui-theme-one-icons/package-lock.json
- packages/veui-theme-one/package-lock.json
- packages/veui/demo/cases/Tooltip.vue
- packages/veui/package-lock.json
- packages/veui/package.json
- packages/veui/src/components/Autocomplete/Autocomplete.vue
- packages/veui/src/components/Overlay.vue
- packages/veui/src/components/RegionPicker.vue
- packages/veui/src/components/Select/OptionGroup.vue
- packages/veui/src/components/Tooltip.vue
- packages/veui/src/mixins/dropdown.js
- packages/veui/src/mixins/overlay.js
- packages/veui/src/utils/helper.js
- packages/veui/test/unit/specs/utils/helper.spec.js
使用 Popper.js 替换 Tether。
- Tether 已经官宣不再维护，虽然 Popper.js 也没有得到太好的频繁维护，但是它仍然是 Bootstrap 依赖的浮层定位库，相比之下可靠性更可控一些。
- 因为 Popper.js 在前一个版本实现了 `flipVariationsByContent` 这个配置功能，使得浮层可以在次级方向上超出视窗时自动翻转方向，这样可以使 `RegionPicker`、`DatePicker` 这样的组件不需要用户来指定定位参数了。
- Tether 有一些初始化时定位的 bug，在 VEUI 之前版本的 Tooltip 等组件第一次展现时都遇到过定位不对的问题，切换后目测已经不再有此问题。
- DLS 版本的目标浏览器已经可以抛弃 IE10-，所以不再有 blocker issue 了。
`Overlay` 组件的 `options` prop（以及多个组件的 `overlay-options` prop）现在都对应于[Popper.js 的 `options` 参数](https://popper.js.org/popper-documentation.html#new_Popper_new).
> 此 PR 将代替 #418。
---
https://github.com/FezVrasta/popper.js/issues/512
https://github.com/FezVrasta/popper.js/pull/754
> !refactor: use Popper.js instead of Tether, update deps

- packages/veui/src/managers/overlay.js
- packages/veui/test/unit/specs/managers/overlay.spec.js
重写 OverlayManager，为了可以注入老的 manager，必须保留以下接口（为 #567 作记录）：
```ts
interface OverlayNode {
id: string
appendTo: (parent: string|OverlayNode, priority: number) => void
toTop: () => void
}
interface CreateNodeOptions {
parentId: number
priority: number
orderChangeCallback: (order: number) => void
}
interface OverlayManager {
setBaseOrder: (order: number) => void
createNode: (options: CreateNodeOptions) => OverlayNode
}
```
> refactor: rewrite overlay manager

- packages/veui/src/mixins/searchable.js
> refactor: add filter to searchable mixin

- .eslintrc.js
- CHANGELOG.md
- packages/veui-theme-dls/components/Tabs.js
- packages/veui-theme-dls/components/tabs.less
- packages/veui/demo/cases/Tabs.vue
- packages/veui/demo/cases/index.js
- packages/veui/src/components/Tabs/Tab.vue
- packages/veui/src/components/Tabs/Tabs.vue
- packages/veui/src/locale/en-US/Tabs.js
- packages/veui/src/locale/zh-Hans/Tabs.js
- packages/veui/src/mixins/controllable.js
- packages/veui/src/mixins/coupled.js
- packages/veui/test/unit/specs/components/Tabs.spec.js
- 移除了添加/移除 Tab 的动效以及 `ui="block"` **<sup>BREAKING</sup>**
- 移除了 `index` prop **<sup>BREAKING</sup>**
- `tabs-extra` slot 更名为 `extra`，且仅包括提示区域的内容，不包括添加按钮 **<sup>BREAKING</sup>**
- 移除了 `tabs-extra-label` 与 `tabs-extra-tip` slot **<sup>BREAKING</sup>**
- `tab-item` scoped slot 现在包含整个按钮/链接，方便替换为自定义实现 **<sup>BREAKING</sup>**
- 新增了 `tab-item-label` scoped slot 用来仅自定义标签内容
- 移除了 `tab-item-extra` scoped slot，`removable` 的 `Tab` 组件始终显示移除按钮 **<sup>BREAKING</sup>**
- 新增了 `panel` slot，在 `Tab` 组件无内联内容时在 `Tabs` panel 内输出自定义内容。
- 在路由模式下，不再自动输出 `<router-view>` 组件，需要通过 `Tab` 的 `default` slot 或 `Tabs` 的 `panel` slot 中进行输出。**<sup>BREAKING</sup>**
---
新的 `Tabs` 仅用 `active` prop 控制激活态，支持受控（包括 `.sync`）/非受控方式。
`Tabs` 的 slot 支持：`panel`、`extra`、`tab-item` <sup>scoped</sup>、`tab-item-label` <sup>scoped</sup>。
> Rewrite Tabs & Tab

- packages/veui/demo/cases/Carousel.vue
- packages/veui/src/components/Carousel.vue
- packages/veui/test/unit/specs/components/Carousel.spec.js
增加了 `lazy` prop，接受 `Boolean|{ preload: Number }`。
当传 `true` 时，默认等同于 `{ preload: 1 }`，即提前加载当前项的前后各 1 项。当传入 `Object` 时可以自行指定提前加载的个数。
同时给 `Carousel` 补充了所有 props 的单测。
> feat: add lazy load for Carousel (#655)

- packages/veui/demo/cases/Select.vue
- packages/veui/src/components/Select/OptionGroup.vue
- packages/veui/src/mixins/menu.js
- packages/veui/test/unit/specs/components/Select/OptionGroup.spec.js
- packages/veui/test/unit/specs/components/Select/Select.spec.js
1. Per #676, rendering inline `Option`/`OptionGroup` with dynamic options may lead to unexpected situation.
2. `before`/`after` slots sometimes do not render correctly after data updates.
> fix(#676): fix option-group rendering issues

- packages/veui-theme-dls/components/button.less
- packages/veui-theme-dls/components/date-picker.less
- packages/veui-theme-dls/components/dropdown.less
- packages/veui-theme-dls/components/filter-panel.less
- packages/veui-theme-dls/components/input-group.less
- packages/veui-theme-dls/components/input.less
- packages/veui-theme-dls/components/number-input.less
- packages/veui-theme-dls/components/pagination.less
- packages/veui-theme-dls/components/search-box.less
- packages/veui-theme-dls/components/select.less
- packages/veui/demo/cases/Input.vue
- packages/veui/src/components/Input.vue
- packages/veui/src/components/NumberInput.vue
- packages/veui/src/components/Progress.vue
- packages/veui/src/components/SearchBox.vue
- packages/veui/src/components/Select/Select.vue
- packages/veui/src/components/TimePicker/TimePicker.vue
- packages/veui/src/components/Transfer/_SelectedPanel.vue
- packages/veui/src/components/Tree/Tree.vue
- packages/veui/test/unit/specs/components/Input.spec.js
- packages/veui/test/unit/specs/components/Select/OptionGroup.spec.js
As we now have an `InputGroup`, slots outside the `Input` itself is no longer useful but makes it harder for styling the input from parent contexts. So in this PR the current `before`/`after` slots are removed and all `prepend`/`append` related slots (for all components) are renamed back to `before`/`after` so that now we keep the semantics consistent with CSS's `::before`/`::after` (before/after *the content* of the element).
> Revert #502, redesign slots of Input

- packages/veui/src/components/NumberInput.vue
解决 parseFloat 遇到设置跨越上限时 val 值没更新
> fix: NumberInput

- packages/veui-theme-dls/components/autocomplete.less
- packages/veui-theme-dls/components/badge.less
- packages/veui-theme-dls/components/button-group.less
- packages/veui-theme-dls/components/button.less
- packages/veui-theme-dls/components/dropdown.less
- packages/veui-theme-dls/components/input-group.less
- packages/veui-theme-dls/components/input.less
- packages/veui-theme-dls/components/loading.less
- packages/veui-theme-dls/components/pagination.less
- packages/veui-theme-dls/components/progress.less
- packages/veui-theme-dls/components/search-box.less
- packages/veui-theme-dls/components/select.less
- packages/veui-theme-dls/components/switch.less
- packages/veui-theme-dls/components/tag.less
- packages/veui/demo/cases/Button.vue
- packages/veui/demo/cases/Input.vue
* Removed built-in `vertical-align: middle` for input components.
* Applied a hack for better default alignment for buttons with icons.
> fix(style): make vertical align less opinionated

- packages/veui-theme-dls/components/uploader.less
修复uploader .veui-uploader-list-media-item 设置overflow:hidden导致file-after slot的内容无法展示出来
> fix: fix Uploader .veui-uploader-list-media-item overflow:hidden bug

- packages/veui-theme-dls/components/table.less
- packages/veui/demo/cases/Table.vue
- packages/veui/src/components/Table/_TableHead.js
- packages/veui/test/unit/specs/components/Table.spec.js
* 整个表头区域点击都会触发排序，除了可获取焦点的元素（认为可以进行点击、交互）
* 鼠标移入除了可交互元素外的部分，也触发排序按钮的高亮
> Trigger sort on the whole table header cell

- packages/veui/src/components/Uploader.vue
- packages/veui/test/unit/specs/components/Uploader.spec.js
fix Uploder组件getScopeValue函数返回丢失name, type等原生file非enumerable属性丢失问题
> fix: fix uploader getScopeValue

- packages/veui-theme-dls/components/uploader.less
- packages/veui/build/dev-server.js
- packages/veui/components.json
- packages/veui/demo/cases/Uploader.vue
- packages/veui/karma.conf.js
- packages/veui/package-lock.json
- packages/veui/package.json
- packages/veui/src/components/Uploader.vue
- packages/veui/src/components/Uploader/Controls.vue
- packages/veui/src/components/Uploader/Uploader.vue
- packages/veui/src/components/Uploader/_Controls.vue
- packages/veui/src/components/Uploader/_FileUploader.vue
- packages/veui/src/components/Uploader/_FileViewer.vue
- packages/veui/src/components/Uploader/_MediaUploader.vue
- packages/veui/src/components/Uploader/_helper.js
- packages/veui/src/components/Uploader/index.js
- packages/veui/src/mixins/upload.js
- packages/veui/src/utils/dom.js
- packages/veui/src/utils/file.js
- packages/veui/test/unit/specs/components/Uploader.spec.js
- packages/veui/test/unit/specs/utils/dom.spec.js
- packages/veui/test/unit/specs/utils/file.spec.js
- packages/veui/vue.config.js
> refactor: simplify Uploader.vue by splitting different views into child components and purify implementations of upload

- packages/veui-theme-dls/components/accordion.less
- packages/veui-theme-dls/components/anchor.less
- packages/veui-theme-dls/components/calendar.less
- packages/veui-theme-dls/components/collapse.less
- packages/veui-theme-dls/components/dialog.less
- packages/veui-theme-dls/components/filter-panel.less
- packages/veui-theme-dls/components/form.less
- packages/veui-theme-dls/components/lightbox.less
- packages/veui-theme-dls/components/menu.less
- packages/veui-theme-dls/components/nav.less
- packages/veui-theme-dls/components/tabs.less
- packages/veui-theme-dls/components/transfer.less
- packages/veui-theme-dls/components/tree.less
- packages/veui-theme-dls/components/uploader.less
有些场景下组件放在设置了不同 `line-height` 的容器下会有问题（比如文档中），需要默认设置一下。
> fix(style): add default line-height for block level components

- packages/veui/src/components/Uploader/Uploader.vue
fix:uploader does not load preview url when type is file #828
> fix:uploader does not load preview url when type is file #828

- CHANGELOG.md
- packages/veui-theme-dls/drag.less
- packages/veui-theme-dls/package-lock.json
- packages/veui/demo/cases/VDragSort.vue
- packages/veui/package-lock.json
- packages/veui/src/components/Uploader/_MediaUploader.vue
- packages/veui/src/directives/drag.js
- packages/veui/src/directives/drag/BaseHandler.js
- packages/veui/src/directives/drag/SortHandler.js
- packages/veui/src/directives/drag/TranslateHandler.js
- packages/veui/src/utils/dom.js
- packages/veui/test/unit/specs/directives/drag.spec.js
- packages/veui/test/unit/specs/directives/drag/SortHandler.spec.js
See the changes for [CHANGELOG.md](https://github.com/ecomfe/veui/compare/fix-drag?expand=1#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed).
> Fix drag related functionalities

- packages/veui-theme-dls/components/button.less
- packages/veui/demo/cases/Button.vue
- packages/veui/src/components/Button.vue
- packages/veui/test/unit/specs/components/Button.spec.js
- packages/veui/test/unit/specs/components/Calendar.spec.js
- packages/veui/test/unit/specs/components/CheckButtonGroup.spec.js
- packages/veui/test/unit/specs/components/Dropdown.spec.js
- packages/veui/test/unit/specs/components/Tabs.spec.js
- packages/veui/test/unit/specs/components/Uploader.spec.js
- packages/veui/test/utils.js
被禁用的按钮现在：
- 渲染为 `<div role="button" aria-disabled="true">...</div>`
- 可接受焦点
- 可响应除 `click` 以外的事件（可触发 Tooltip/Popover 等展示）
> feat: disabled buttons can receive focus and trigger hover, etc.

- CHANGELOG.md
- packages/veui-theme-dls/components/popover.less
- packages/veui-theme-dls/components/tooltip.less
- packages/veui/demo/cases/Popover.vue
- packages/veui/demo/cases/Tooltip.vue
- packages/veui/src/components/DatePicker.vue
- packages/veui/src/components/Menu/Menu.vue
- packages/veui/src/components/Select/OptionGroup.vue
- packages/veui/src/components/Tooltip.vue
- packages/veui/src/mixins/dropdown.js
- packages/veui/src/mixins/overlay.js
...and refactored a little for components depend on the `overlay` mixin. (rename `localOverlayOptions` to `defaultOverlayOptions`)
Closes #904.
> Add `aim-center` support for Tooltip & Popover

- packages/veui-theme-dls/components/table.less
- packages/veui/demo/cases/Table.vue
- packages/veui/demo/cases/Tooltip.vue
- packages/veui/src/components/Table/Column.vue
- packages/veui/src/components/Table/_HeadCell.js
- packages/veui/src/components/Table/_Row.js
- packages/veui/src/components/Tooltip.vue
- packages/veui/src/directives/tooltip.js
- packages/veui/src/managers/tooltip.js
- packages/veui/test/unit/specs/components/Table.spec.js
- packages/veui/test/unit/specs/directives/tooltip.spec.js
- packages/veui/test/unit/specs/managers/tooltip.spec.js
- packages/veui/test/utils.js
* `v-tooltip` 增加 `overflow` modifier
* 修正 `v-tooltip` 全局销毁逻辑
* `Column` 增加 `tooltip: boolean | ((item: Object) => string)` prop
* `Column` 的 Popover 浮层默认定位修正为 `top`
* Table 默认样式增加固定 1 行样式
Closes #918.
> feat: add overflow tooltip for tooltip directive and table column

- packages/veui/src/components/Overlay.vue
- packages/veui/src/directives/drag/SortHandler.js
- packages/veui/src/utils/dom.js
- packages/veui/test/unit/specs/components/Calendar.spec.js
* bring the timing of the `afteropen` event for `Overlay` forward to immediately after its content is rendered to DOM
* add `getScrollContainerOffset` in `utils/dom` to calculate the relative position of an element against its scroll container
* make `scrollIntoView` and `scrollToAlign` insensitive to transforms
* fix test cases for `Calendar`
Closes #939
> fix: make scrollIntoView immune to transform

- packages/veui-theme-dls/components/button-group.less
- packages/veui-theme-dls/components/button.less
- packages/veui/demo/cases/Button.vue
- packages/veui/karma.conf.js
- packages/veui/src/components/Button.vue
- packages/veui/test/unit/specs/components/AlertBox.spec.js
- packages/veui/test/unit/specs/components/Button.spec.js
- packages/veui/test/unit/specs/components/ConfirmBox.spec.js
- packages/veui/test/unit/specs/components/Dialog.spec.js
- packages/veui/test/unit/specs/components/Drawer.spec.js
- packages/veui/test/unit/specs/components/Input.spec.js
- packages/veui/test/unit/specs/components/NumberInput.spec.js
- packages/veui/test/unit/specs/components/PromptBox.spec.js
- packages/veui/test/unit/specs/components/SearchBox.spec.js
- packages/veui/test/unit/specs/components/Table.spec.js
- packages/veui/test/unit/specs/components/Uploader.spec.js
目前 `Button` 组件为了在 `disabled` 状态下可以支持鼠标悬浮事件、接收焦点，实现方式是 `disabled` 状态下用 `<div>` 渲染。但这样在动态切换 `disabled` 时丢失了 transition 效果。所以这个 PR 将 `Button` 的实现统一为 `div > button` 的结构，并且尽可能保持原生的按钮功能：
- 支持点击 <kbd>enter</kbd> 触发 `click`
- 支持按下 <kbd>space</kbd> 触发 active 视觉效果，抬起时触发 `click`，点击完阻止默认的页面滚动
- 内部依然有一个原生 `<button>` 但不绑定任何事件，用来触发按钮的默认行为，比如 `type="submit"` 时触发外部表单提交等
- 普通 DOM attr 输出到 `<div>`，特殊属性输出到 `<button>`
- 用 `role="button"` 标注 ARIA 语义信息
> refactor: keep button transition when toggling disabled

- packages/veui/src/components/AlertBox.vue
- packages/veui/src/components/ConfirmBox.vue
- packages/veui/src/components/Dialog.vue
- packages/veui/src/components/PromptBox.vue
- packages/veui/types/components/alert-box.d.ts
- packages/veui/types/components/confirm-box.d.ts
- packages/veui/types/components/dialog.d.ts
- packages/veui/types/components/prompt-box.d.ts
- pass down listeners instead of re-emit events
- add `afteropen` event
- fix `.d.ts`
> feat: improve alert/confirm/prompt-box events

- packages/babel-plugin-veui/src/treeshake.js
- packages/babel-plugin-veui/test/fixtures/treeshake/expected.js
- packages/babel-plugin-veui/test/fixtures/treeshake/source.js
...when looking for component names.
> fix: babel plugin should match the whole identifier

- packages/veui/demo/cases/Input.vue
- packages/veui/package.json
- packages/veui/src/components/DatePicker.vue
- packages/veui/src/components/Input.vue
- packages/veui/src/components/NumberInput.vue
- packages/veui/src/components/TimePicker/TimePicker.vue
- packages/veui/src/utils/bom.js
- packages/veui/test/unit/specs/components/DatePicker.spec.js
- packages/veui/test/unit/specs/components/NumberInput.spec.js
- packages/veui/test/unit/specs/components/TimePicker/TimePicker.spec.js
- pnpm-lock.yaml
- Added a `mask` prop to `Input` but let's keep it internal for now, as we may switch to other low-level implementations in the future and we tend to prevent vendor lock-in ATM.
- Used a forked version of [`maska`](https://github.com/beholdr/maska) as it doesn't support optional token yet and the author seems to be inactive (I made a PR anyway https://github.com/beholdr/maska/pull/87).
- Disabled in Firefox as the order of `input` event handlers and microtasks in it is different from others, which makes it very tricky to coordinate our controlled input and `maska`'s DOM manipulation in Firefox.
- Technically the masks can be stricter but it would be rather complicated.
---
Update: `maska@2` will come with an optional token so we'll move to it later.
> feat: add input mask for NumberInput, DatePicker and TimePicker

- packages/veui/demo/cases/Table.vue
- packages/veui/src/components/Table/Column.vue
- packages/veui/src/components/Table/Table.vue
- packages/veui/src/components/Table/_Head.js
- packages/veui/test/unit/specs/components/Table.spec.js
There seems no need to manually force update table head/foot now.
> refactor: remove manually updating table parts and add test cases

- packages/veui/demo/cases/Autocomplete.vue
- packages/veui/src/components/Autocomplete/Autocomplete.vue
- packages/veui/src/components/Autocomplete/_AutocompleteBase.vue
- packages/veui/test/unit/specs/components/Autocomplete.spec.js
`strict` prop should control all component built-in validation or related features. Take `TagInput` as an example:
We have both `max` for tag count and `maxlength` for tag text length. The `strict` attribute can be a `boolean` or `{ max?: boolean, maxlength?: boolean }`. When it is a `boolean`, it is equivalent to enabling strict mode for both rules at the same time. We use `useStrict` to enforce consistency across different components.
> feat: add useStrict

- packages/veui-theme-dls/components/toast-list.less
- packages/veui-theme-dls/components/toast.less
- packages/veui/demo/cases/Plugins.vue
- packages/veui/demo/cases/Table.vue
- packages/veui/src/components/Toast.vue
- packages/veui/src/components/ToastList.vue
- packages/veui/src/directives/tooltip.js
- packages/veui/src/managers/alert.js
- packages/veui/src/managers/confirm.js
- packages/veui/src/managers/prompt.js
- packages/veui/src/managers/simple-dialog.js
- packages/veui/src/managers/toast.js
- packages/veui/src/managers/tooltip.js
- packages/veui/src/utils/dom.js
- packages/veui/src/utils/helper.js
- packages/veui/test/unit/specs/directives/tooltip.spec.js
- packages/veui/test/utils.js
* plugins: `$alert` / `$confirm` / `$prompt` / `$toast`
* respect `theme` global config by default
* can be overridden with `theme` option
* directive: `tooltip`
* automatically derived from the theme of the target element's closest component
Made some other necessary changes for the above feature.
> feat: support theme for imperatively created components
