ecomfe/veui

- demo/cases/DatePicker.vue
- demo/cases/Pager.vue
- src/components/Calendar.vue
- src/components/DatePicker.vue
- src/components/Dropdown.vue
- src/components/Pager.vue
- src/components/Select/Select.vue
- src/components/Table/Body.js
- src/components/Table/Table.vue
- src/directives/outside.js
- src/mixins/dropdown.js
- src/styles/theme-default/dropdown.less
- src/styles/theme-default/mixins.less
* add Table selected row style
* rename `hrefTpl` to `to` for Pager
* unify dropdown to mixin
* fix that `v-outside` failed to work on native elements
* implement `DatePicker`
* fix year view for Calendar according to new design
> 多处修改，包括统一下拉框实现方式等

- demo/cases/Calendar.vue
- demo/cases/DatePicker.vue
- demo/cases/index.js
- src/components/DatePicker.vue
- src/components/Dropdown.vue
- src/components/Pager.vue
- src/components/Select/Select.vue
- src/mixins/dropdown.js
- src/styles/theme-default/common.less
- src/styles/theme-default/mixins.less
* 增加日期范围选择
* Pager 增加 `pagesizechange` 事件
* 在非高分屏下关闭字体抗锯齿
> 范围选择、分页事件添加

- demo/cases/Input.vue
- src/components/Input.vue
- src/components/Select/Select.vue
- src/components/Uploader.vue
- src/mixins/input.js
> input mixin 小调整

- src/mixins/dropdown.js
> dropdown tether组合限制

- src/components/Tooltip.vue
> Tooltip大小调整

- packages/veui/src/components/Searchbox.vue
如果不加type=button，默认就是submit,当处在一个form里面，按enter会触发第一个button的click事件。。
第一个button也就是 clear...
https://stackoverflow.com/a/12914700
> add button attribute `type=button`

- CHANGELOG.md
- packages/veui-theme-x/components/progress.less
- packages/veui/demo/cases/Progress.vue
- packages/veui/src/components/Progress.vue
* `type`: `String`
可选 `'bar'` / `'circular'`，进度条形状。
* `desc`: `Boolean`
是否显示文字描述。
* `value`: `Number`
进度值。为 `min`、`max` 之间的一个值。
* `precision`: `Number`
显示数值时保留的小数位数。默认 `0`。
* `min`: `Number`
最小值。默认 `0`。
* `max`: `Number`
最大值。默认 `1`。
* `state`: `String`
进度状态。样式默认支持 `success` / `alert`。
* `auto-succeed`: `Boolean`
进度完成时自动添加 `success` 状态。
* `default`（scoped）
文字描述的内容。参数为 `percent`、`value`、`state`。
> 增加 Progress 组件

- packages/veui/demo/cases/Pager.vue
- packages/veui/src/components/Pager.vue
调用者使用 .sync 来同步多个 Pager 实例间的 pageSize 值。如下代码，
* 当其中一个被用户修改了 pageSize 时，另一个也会跟着改变。
* 调用者主动更新 pageSize 值时，将覆盖用户设置。
```vue
<Pager :page-size.sync="pageSize" />
<Pager :page-size.sync="pageSize" />
```
> Pager组件 pageSize 支持 .sync

- packages/veui/demo/cases/Tooltip.vue
- packages/veui/src/components/Tooltip.vue
> bugfix: let tooltip support overlayOptions's overwrite

- .eslintrc.js
- .postcssrc
- package-lock.json
- package.json
- packages/babel-plugin-veui/src/index.js
- packages/veui-loader/src/index.js
- packages/veui-theme-one/components/Tabs.js
- packages/veui-theme-one/components/tabs.less
- packages/veui/src/components/Tabs/Tabs.vue
- packages/veui/test/unit/specs/managers/config.spec.js
* 一些代码格式调整
* Tabs 的 HTML 结构修正，图标分离
* 添加 config 的测试 case
> Refactor Tabs

- packages/veui/src/components/Alert.vue
- packages/veui/src/components/AlertBox.vue
- packages/veui/src/components/ConfirmBox.vue
- packages/veui/src/components/Dialog.vue
- packages/veui/src/components/PromptBox.vue
> 为 Dialog 等组件提供 WAI-ARIA 支持

- packages/veui-theme-one/components/checkbox.less
- packages/veui-theme-one/components/radio.less
- packages/veui/src/components/Breadcrumb.vue
- packages/veui/src/components/ButtonGroup.vue
- packages/veui/src/components/CheckButtonGroup.vue
- packages/veui/src/components/Checkbox.vue
- packages/veui/src/components/CheckboxGroup.vue
- packages/veui/src/components/Radio.vue
- packages/veui/src/components/RadioButtonGroup.vue
- packages/veui/src/components/RadioGroup.vue
- packages/veui/src/mixins/input.js
> 为 ButtonGroup 等组件添加 WAI-ARIA 支持

- packages/veui-theme-one/components/calendar.less
- packages/veui/demo/cases/Calendar.vue
- packages/veui/src/components/Calendar.vue
- packages/veui/src/utils/math.js
- packages/veui/test/unit/specs/utils/math.spec.js
> 为 Calendar 组件提供键盘导航及 ARIA 支持

- packages/veui/src/components/Link.vue
- packages/veui/src/components/Pagination.vue
> 为 Pagination 组件添加 ARIA 支持

- packages/veui-theme-one/components/Searchbox.js
- packages/veui-theme-one/components/searchbox.less
- packages/veui/demo/cases/Searchbox.vue
- packages/veui/src/components/Searchbox.vue
以下两个属性放到 Input 中实现：
1. clearable
2. placeholder 兼容方案
用 Input 实现，不存在 zIndex 的问题，顺带解决 #281
> 重构 Searchbox

- CHANGELOG.md
- packages/veui/src/components/Checkbox.vue
- packages/veui/src/components/Input.vue
- packages/veui/src/components/Radio.vue
- packages/veui/src/components/Schedule.vue
- packages/veui/src/directives/drag/TranslateHandler.js
- packages/veui/test/unit/specs/components/Calendar.spec.js
- packages/veui/test/unit/specs/components/Checkbox.spec.js
- packages/veui/test/unit/specs/components/DatePicker.spec.js
- packages/veui/test/unit/specs/components/Input.spec.js
- packages/veui/test/unit/specs/components/NumberInput.spec.js
- packages/veui/test/unit/specs/components/Overlay.spec.js
- packages/veui/test/unit/specs/components/Radio.spec.js
- packages/veui/test/unit/specs/components/RegionPicker.spec.js
- packages/veui/test/unit/specs/components/Schedule.spec.js
- packages/veui/test/unit/specs/components/Searchbox.spec.js
- packages/veui/test/unit/specs/managers/config.spec.js
- packages/veui/test/unit/specs/managers/overlay.spec.js
以及用 Prettier 格式化了一下 test spec。
> 调整 Checkbox 的 `checked` 语义

- packages/veui-theme-one/components/searchbox.less
- packages/veui/src/components/Searchbox.vue
1. 修复：#308 
2. readonly 模式下，将 button 转成 diasabled
> 更新 Searchbox

- packages/veui/src/components/Schedule.vue
> 为 Schedule 组件添加 ARIA 支持

- packages/veui/src/components/Table/Table.vue
- packages/veui/src/components/Table/_TableBody.js
- packages/veui/src/components/Table/_TableFoot.js
- packages/veui/src/components/Table/_TableHead.js
- packages/veui/src/components/Table/_TableRow.js
> 为 Table 组件添加 ARIA 支持

- packages/veui/src/components/Form/Field.vue
- packages/veui/src/components/Form/Fieldset.vue
> 为 Fieldset 组件添加 ARIA 支持

- CHANGELOG.md
- packages/veui-theme-one/components/progress.less
- packages/veui-theme-one/components/steps.less
- packages/veui-theme-one/components/uploader.less
- packages/veui/src/components/NumberInput.vue
- packages/veui/src/components/Pagination.vue
- packages/veui/src/components/Progress.vue
- packages/veui/src/components/Steps.vue
- packages/veui/src/components/Uploader.vue
* fix: fix issue when either of min/max is 0 for NumberInput
* fix: remove padding, fix auto-succeed for Progress
* refactor: simplify class name
* refactor: tweak event callback params for Pagination redirect and Steps
* fix: remove extra margin
> Multiple fix

- package-lock.json
- packages/babel-plugin-veui/package-lock.json
- packages/veui-loader/package-lock.json
- packages/veui-loader/src/index.js
- packages/veui-theme-one/.babelrc
- packages/veui-theme-one/package-lock.json
- packages/veui-theme-one/package.json
- packages/veui/build/veui-loader-options.js
- packages/veui/build/webpack.base.conf.js
- packages/veui/jest.config.js
- packages/veui/package-lock.json
- packages/veui/package.json
- packages/veui/src/components/Dialog.vue
- packages/veui/src/components/Icon.vue
- packages/veui/src/managers/focus.js
- packages/veui/test/unit/specs/components/Dialog.spec.js
- packages/veui/test/veui-jest.js
* refactor Dialog to support preventing default behavior asynchronously with new function prop
* fix test by injecting theme in jest environment
> Dialog 重构 & Jest transform 支持注入 theme

- CHANGELOG.md
- packages/veui/demo/cases/Table.vue
- packages/veui/src/components/Table/Column.vue
- packages/veui/src/components/Table/Table.vue
- packages/veui/src/components/Table/_TableFoot.js
- packages/veui/src/components/Table/_TableRow.js
- packages/veui/src/components/Toast.vue
- packages/veui/src/components/ToastList.vue
- packages/veui/src/components/Tooltip.vue
* 修正 `Table` slot `foot` 的渲染逻辑
* 为 `Column` 的 `span` function prop 增加新参数
* 为 `Toast` 增加 prop `open` 及 slot
> fix: foot slot for Table, default slot for Toast

- packages/veui/src/components/Table/Table.vue
adjust table default slot position to render columns during the first rendering
> refactor: adjust table default slot position

- CHANGELOG.md
- packages/veui-theme-one/components/pagination.less
- packages/veui-theme-one/components/slider.less
- packages/veui-theme-one/components/tabs.less
- packages/veui-theme-one/components/tooltip.less
- packages/veui-theme-one/package.json
- packages/veui/demo/App.vue
- packages/veui/demo/cases/Form.vue
- packages/veui/demo/cases/Slider.vue
- packages/veui/demo/cases/Tabs.vue
- packages/veui/demo/cases/Tooltip.vue
- packages/veui/src/components/Input.vue
- packages/veui/src/components/Overlay.vue
- packages/veui/src/components/Pagination.vue
- packages/veui/src/components/Searchbox.vue
- packages/veui/src/components/Slider.vue
- packages/veui/src/components/Tabs/Tabs.vue
- packages/veui/src/components/Tooltip.vue
- packages/veui/src/directives/outside.js
* `Tooltip` `custom` prop &rarr; `target="custom"`
* Internal `pager` &rarr; `pagination`
* `Slider` `step` + `min` bug fix
* Refine `Slider` tooltip display
* Refine `Overlay` logic
> Minor refactor

- packages/babel-plugin-veui/test/index.js
- packages/veui-loader/package.json
- packages/veui-loader/src/index.js
原来的laoder和plugin可能有些兼容问题，应该是win下才有的，修改了一下，项目正常启动，测试也全部通过了
> fix path can't resolve & unite test line break sign

- packages/veui-theme-one/components/number-input.less
- packages/veui-theme-one/components/radio.less
- packages/veui/src/components/Transfer/Transfer.vue
- packages/veui/test/unit/specs/components/Dialog.spec.js
- packages/veui/test/unit/specs/components/Transfer.spec.js
Fix the problem that Transfer is not updating candidate items when `datasource` is changed.
> Fix Transfer

- packages/veui/src/components/Transfer/Transfer.vue
- packages/veui/test/unit/specs/components/Transfer.spec.js
> 修复transfer中selected数组清空无效的问题

- packages/veui/src/components/Table/Table.vue
> fix: computed colspan by realColumns

- packages/veui/src/components/Transfer/Transfer.vue
- packages/veui/src/components/Transfer/_CandidatePanel.vue
- packages/veui/src/components/Transfer/_SelectedPanel.vue
- packages/veui/src/components/Tree/Tree.vue
- packages/veui/src/components/Tree/_TreeNode.vue
* Implement `focus` method for `Transfer`
* Refine keyboard navigation for `Tree`
* Refactor `_TreeNde` with clearer template
* Add ARIA annotation for `Tree`
> A11y for Transfer related components

- packages/veui/src/components/DatePicker.vue
- packages/veui/src/components/Dropdown.vue
- packages/veui/src/components/Searchbox.vue
- packages/veui/src/components/Select/Select.vue
- packages/veui/src/mixins/dropdown.js
Adding correct aria connection for dropdown overlays.
> fix: add aria-owns for dropdown components

- packages/veui/src/components/Overlay.vue
- packages/veui/src/components/Select/OptionGroup.vue
- packages/veui/src/components/Select/Select.vue
- packages/veui/src/components/Tabs/Tab.vue
- packages/veui/src/components/Tabs/Tabs.vue
(Current ARIA annotation of the Select component is the same with [Dijit](https://dojotoolkit.org/reference-guide/1.10/dijit/form/Select.html#dijit-form-select).)
> fix: refine aria annotations for Select and Tabs

- CHANGELOG.md
- packages/veui/package-lock.json
- packages/veui/package.json
- packages/veui/src/components/Schedule.vue
- packages/veui/src/directives/longpress.js
- packages/veui/test/unit/specs/directives/longpress.spec.js
- packages/veui/test/utils.js
> refactor: use vue-directive-normalizer for v-longpress

- packages/veui/jest.config.js
- packages/veui/src/directives/drag.js
- packages/veui/test/unit/env.js
- packages/veui/test/unit/specs/directives/drag.spec.js
> refactor: use vue-directive-normalizer and refactor drag

- packages/veui/demo/cases/index.js
- packages/veui/test/unit/specs/components/Alert.spec.js
- packages/veui/test/unit/specs/components/AlertBox.spec.js
* test:add test cases for AlertBox
* feat: add demo case entry for AlertBox
* test: optimize unit test for Alert
> test:add test cases for AlertBox

- packages/veui/src/managers/rules/numeric.js
- packages/veui/test/unit/specs/managers/rules/numeric.spec.js
在输入框里输入0，传过去的val会转换为'0'，isNumber()会是false，然后就会进行正则判断
> fix: modify the reg so that 0 won't be judged as non-numeric

- packages/veui-theme-dls/common.less
- packages/veui-theme-dls/components/ButtonGroup.js
- packages/veui-theme-dls/components/CheckButtonGroup.js
- packages/veui-theme-dls/components/RadioButtonGroup.js
- packages/veui-theme-dls/components/button-group.less
- packages/veui-theme-dls/components/button.less
- packages/veui-theme-dls/grouped-button.less
- packages/veui/demo/cases/Button.vue
- packages/veui/demo/cases/ButtonGroup.vue
- packages/veui/demo/cases/CheckButtonGroup.vue
- packages/veui/demo/cases/index.js
- packages/veui/src/components/Button.vue
- packages/veui/src/components/CheckButtonGroup.vue
- packages/veui/src/components/RadioButtonGroup.vue
- ButtonGroup
- RadioButtonGroup
- CheckButtonGroup
> feat: add button groups

- packages/veui/demo/cases/Select.vue
- packages/veui/src/components/Select/Select.vue
[Issues #503](https://github.com/ecomfe/veui/issues/503)
> fix: localvalue assignment on mounted to avoid get refs.options exception

- packages/veui/src/components/Searchbox.vue
- packages/veui/test/unit/specs/components/Searchbox.spec.js
[Issue #506](https://github.com/ecomfe/veui/issues/506)
> fix: searchbox should not show suggestions on readonly state

- packages/veui-theme-dls/common.less
- packages/veui-theme-dls/components/CheckButtonGroup.js
- packages/veui-theme-dls/components/Input.js
- packages/veui-theme-dls/components/NumberInput.js
- packages/veui-theme-dls/components/button-group.less
- packages/veui-theme-dls/components/check-button-group.less
- packages/veui-theme-dls/components/field.less
- packages/veui-theme-dls/components/input.less
- packages/veui-theme-dls/components/number-input.less
- packages/veui-theme-dls/components/switch.less
- packages/veui-theme-dls/package-lock.json
- packages/veui-theme-dls/package.json
- packages/veui/demo/cases/CheckButtonGroup.vue
- packages/veui/demo/cases/Input.vue
- packages/veui/demo/cases/NumberInput.vue
- packages/veui/demo/cases/Select.vue
- packages/veui/demo/cases/index.js
- packages/veui/src/components/Button.vue
- packages/veui/src/components/CheckButtonGroup.vue
- packages/veui/src/components/Input.vue
- packages/veui/src/components/Link.vue
- packages/veui/src/components/NumberInput.vue
- packages/veui/src/mixins/ui.js
- packages/veui/src/utils/helper.js
- packages/veui/test/unit/specs/components/Alert.spec.js
- packages/veui/test/unit/specs/components/Input.spec.js
- packages/veui/test/unit/specs/components/Searchbox.spec.js
- packages/veui/test/unit/specs/utils/helper.spec.js
Refactor Input, NumberInput according to DLS.
> Switch Input/NumberInput to DLS

- packages/veui-theme-dls/components/Accordion.js
- packages/veui-theme-dls/components/Collapse.js
- packages/veui-theme-dls/components/accordion.less
- packages/veui-theme-dls/components/checkbox-group.less
- packages/veui-theme-dls/components/collapse.less
- packages/veui-theme-dls/components/radio-group.less
- packages/veui-theme-dls/package-lock.json
- packages/veui-theme-dls/package.json
- packages/veui/components.json
- packages/veui/demo/cases/Collapse.vue
- packages/veui/demo/cases/index.js
- packages/veui/src/components/Accordion.vue
- packages/veui/src/components/Collapse.vue
- packages/veui/src/components/Form/Field.vue
- packages/veui/src/components/Label.vue
- packages/veui/src/mixins/coupled.js
- packages/veui/src/mixins/input.js
- packages/veui/src/utils/helper.js
- packages/veui/test/unit/specs/components/Accordion.spec.js
- packages/veui/test/unit/specs/components/Collapse.spec.js
- packages/veui/vue.config.js
* feat: add Accordion and Collapse
* feat: add style for Radio/Checkbox groups
* refactor: refactored input mixin
> feat: add Accordion and Collapse

- packages/veui-theme-dls/components/Accordion.js
- packages/veui-theme-dls/components/AlertBox.js
- packages/veui-theme-dls/components/Dialog.js
- packages/veui-theme-dls/components/alert-box.less
- packages/veui-theme-dls/components/confirm-box.less
- packages/veui-theme-dls/components/dialog.less
- packages/veui-theme-dls/components/drawer.less
- packages/veui-theme-dls/components/overlay.less
- packages/veui-theme-dls/components/prompt-box.less
- packages/veui-theme-dls/mixins.less
- packages/veui-theme-dls/package-lock.json
- packages/veui-theme-dls/package.json
- packages/veui/components.json
- packages/veui/demo/cases/AlertBox.vue
- packages/veui/demo/cases/Dialog.vue
- packages/veui/demo/cases/Drawer.vue
- packages/veui/demo/cases/index.js
- packages/veui/package-lock.json
- packages/veui/package.json
- packages/veui/src/components/AlertBox.vue
- packages/veui/src/components/Dialog.vue
- packages/veui/src/components/Drawer.vue
- packages/veui/src/components/Overlay.vue
- packages/veui/src/components/Searchbox.vue
- packages/veui/src/mixins/ui.js
- packages/veui/src/utils/helper.js
- packages/veui/test/unit/specs/components/AlertBox.spec.js
- packages/veui/test/unit/specs/components/Drawer.spec.js
- packages/veui/test/unit/specs/utils/dom.spec.js
- packages/veui/vue.config.js
> Switch Dialog/AlertBox/ConfirmBox/PromptBox to DLS

- packages/veui/demo/cases/Input.vue
- packages/veui/demo/cases/NumberInput.vue
- packages/veui/src/components/Input.vue
- packages/veui/src/components/NumberInput.vue
> fix: Input placeholder bug & NumberInput change event bug

- packages/veui-theme-dls/common.less
- packages/veui-theme-dls/components/Progress.js
- packages/veui-theme-dls/components/progress.less
- packages/veui/demo/cases/Progress.vue
- packages/veui/src/components/Progress.vue
- Added `radius`/`strokeWidth` prop to `Progress`.
- `status` can now only be one of `success` or `error`.
> feat: switch Progress to DLS

- packages/veui-theme-dls/components/searchbox.less
- packages/veui/demo/cases/Searchbox.vue
- packages/veui/demo/cases/index.js
- packages/veui/src/components/Searchbox.vue
- packages/veui/test/unit/specs/components/Searchbox.spec.js
- Searchbox 使用 OptionGroup
- Searchbox 支持上下切换选项
- 去除 demo 里 loading 组件的重复注册路由
> refactor: use optiongroup as searchbox's menu & enhance searchbox's keyboard management

- packages/veui-theme-dls/components/dialog.less
- packages/veui-theme-dls/components/embedded.less
- packages/veui/components.json
- packages/veui/demo/cases/Dialog.vue
- packages/veui/demo/cases/Embedded.vue
- packages/veui/demo/cases/Overlay.vue
- packages/veui/demo/cases/Slider.vue
- packages/veui/demo/cases/index.js
- packages/veui/src/components/Dialog.vue
- packages/veui/src/components/Embedded.vue
- packages/veui/src/components/Overlay.vue
- packages/veui/test/unit/specs/components/Embedded.spec.js
- add new component `Embedded`
- add `inline` prop for `Dialog` and `Overlay`
- refactor `Overlay` with JSX
> feat: add Embedded

- CHANGELOG.md
- packages/veui-loader/test/index.js
- packages/veui-theme-dls/components/Calendar.js
- packages/veui-theme-dls/components/DatePicker.js
- packages/veui-theme-dls/components/calendar.less
- packages/veui-theme-dls/components/date-picker.less
- packages/veui-theme-dls/package-lock.json
- packages/veui/components.json
- packages/veui/demo/cases/Calendar.vue
- packages/veui/demo/cases/DatePicker.vue
- packages/veui/demo/cases/index.js
- packages/veui/package-lock.json
- packages/veui/package.json
- packages/veui/src/components/Calendar.vue
- packages/veui/src/components/Calendar/Calendar.vue
- packages/veui/src/components/Calendar/_InfiniteScroll.vue
- packages/veui/src/components/Calendar/index.js
- packages/veui/src/components/DatePicker.vue
- packages/veui/src/components/Overlay.vue
- packages/veui/src/locale/en-US/Calendar.js
- packages/veui/src/locale/en-US/DatePicker.js
- packages/veui/src/locale/zh-Hans/Calendar.js
- packages/veui/src/locale/zh-Hans/DatePicker.js
- packages/veui/src/utils/date.js
- packages/veui/test/unit/specs/components/Calendar.spec.js
- packages/veui/test/unit/specs/components/DatePicker.spec.js
- packages/veui/test/unit/specs/utils/date.spec.js
1. <del>样式还没写完...（disabled样式）</del>
2. month/year range 的部分我最终还是先把 transition 拿掉了🙃，再想想
3. <del>单测还没改，覆盖率不够</del>
4. <del> inner封装进Overlay</del>
5. <del>open overlay 时重置 panel 的当前时间</del>
6. 滚动更加精确
7. <del>焦点控制</del> type=year 先不管吧
> feat: switch Calendar to DLS

- packages/veui-theme-dls/components/tree.less
- packages/veui-theme-dls/package-lock.json
- packages/veui-theme-dls/package.json
- packages/veui/demo/cases/Tree.vue
- packages/veui/src/components/Select/Select.vue
- packages/veui/src/components/Tree/Tree.vue
- packages/veui/src/components/Tree/_TreeNode.vue
- packages/veui/test/unit/specs/components/Tree.spec.js
现在 `Tree` 的实现好像有点奇怪，`TreeNode` 其实是 node group，如果实现成单个 node，是不是会简单点？
> feat: selectable tree and remove `itemClick` prop

- CHANGELOG.md
- packages/veui/src/components/Button.vue
- packages/veui/test/unit/specs/components/Button.spec.js
> !feat: remove loading slot for Button

- packages/veui-theme-dls/common.less
- packages/veui-theme-dls/normalize.less
- packages/veui-theme-dls/variables.less
编译时可以指定 `@veui-root-selector`，使全局样式仅在指定范围内输出。
> feat: add `@veui-root-selector` to make global styles scopable

- packages/veui-theme-dls/components/table.less
- packages/veui/demo/cases/Table.vue
- packages/veui/src/components/Table/Table.vue
- packages/veui/src/components/Table/_ColGroup.js
- packages/veui/src/components/Table/_Sorter.vue
- packages/veui/src/components/Table/_TableBody.js
- packages/veui/src/components/Table/_TableFoot.js
- packages/veui/src/components/Table/_TableHead.js
- packages/veui/src/components/Table/_TableRow.js
- packages/veui/src/locale/zh-Hans/Table.js
- packages/veui/src/mixins/table.js
> fix: table scroll event listener initialization

- packages/veui/demo/cases/Overlay.vue
- packages/veui/src/components/Overlay.vue
- packages/veui/src/utils/dom.js
- packages/veui/src/utils/helper.js
... and support scoped styles on overlay boxes.
> Minor tweak for portal logic

- .eslintrc.js
- CHANGELOG.md
- package-lock.json
- packages/babel-plugin-veui/package-lock.json
- packages/babel-plugin-veui/package.json
- packages/babel-plugin-veui/test/index.js
- packages/veui-loader/package-lock.json
- packages/veui-theme-dls-icons/package-lock.json
- packages/veui-theme-dls-icons/package.json
- packages/veui-theme-dls/components/badge.less
- packages/veui-theme-dls/components/carousel.less
- packages/veui-theme-dls/components/dropdown.less
- packages/veui-theme-dls/package-lock.json
- packages/veui-theme-dls/package.json
- packages/veui-theme-one-icons/package-lock.json
- packages/veui-theme-one-icons/package.json
- packages/veui/demo/cases/ButtonGroup.vue
- packages/veui/package-lock.json
- packages/veui/package.json
- packages/veui/src/components/ButtonGroup.vue
- packages/veui/src/components/Select/Option.vue
- chore: fix test script for babel-plugin-veui
- chore: update deps and changelog
- chore: move veui to babel-plugin-veui's peerDependencies
- fix: stop scroll last selected option into view for multiple Select
- fix: fix search box on top of the dropdown menu for Dropdown, refine styles for badge and carousel
- fix: emit value as event only when it is a string for ButtonGroup
> Multiple fixes

- package.json
- packages/veui/demo/cases/Select.vue
- packages/veui/src/components/Select/OptionGroup.vue
- packages/veui/src/components/Select/Select.vue
- packages/veui/src/components/Tabs/Tab.vue
- packages/veui/src/directives/outside.js
- packages/veui/src/mixins/menu.js
- packages/veui/src/utils/dom.js
- packages/veui/src/utils/helper.js
- packages/veui/test/unit/specs/components/Select/OptionGroup.spec.js
- focus lock for searchable multiple select
- fix overlay target for OptionGroup with `position: popup`
> feat: add before/after slot for OptionGroup

- packages/veui/package-lock.json
- packages/veui/package.json
- packages/veui/src/components/DatePicker.vue
- packages/veui/src/utils/date.js
> upgrade date-fns to 2.11.1

- .stylelintrc
- packages/veui-theme-dls/components/breadcrumb-item.less
- packages/veui-theme-dls/components/input.less
- packages/veui-theme-dls/components/table.less
- packages/veui-theme-dls/components/tabs.less
- packages/veui-theme-dls/components/textarea.less
- packages/veui/demo/cases/Input.vue
...along with some style tweaks.
> fix(#653): fix tab item spacing on some browsers (\wo ResizeObserver)

- packages/veui/src/components/RegionPicker.vue
> fix: region id can be number 0 for RegionPicker

- packages/veui-theme-dls/common.less
- packages/veui-theme-dls/components/anchor.less
- packages/veui-theme-dls/components/breadcrumb-item.less
- packages/veui-theme-dls/components/button-group.less
- packages/veui-theme-dls/components/button.less
- packages/veui-theme-dls/components/calendar.less
- packages/veui-theme-dls/components/carousel.less
- packages/veui-theme-dls/components/check-button-group.less
- packages/veui-theme-dls/components/date-picker.less
- packages/veui-theme-dls/components/dropdown.less
- packages/veui-theme-dls/components/filter-panel.less
- packages/veui-theme-dls/components/input.less
- packages/veui-theme-dls/components/pagination.less
- packages/veui-theme-dls/components/radio.less
- packages/veui-theme-dls/components/select.less
- packages/veui-theme-dls/components/slider.less
- packages/veui-theme-dls/components/steps.less
- packages/veui-theme-dls/components/switch.less
- packages/veui-theme-dls/components/table.less
- packages/veui-theme-dls/components/tabs.less
- packages/veui-theme-dls/components/tag.less
- packages/veui-theme-dls/components/textarea.less
- packages/veui-theme-dls/components/toast.less
- packages/veui-theme-dls/components/tooltip.less
- packages/veui-theme-dls/components/uploader.less
- packages/veui-theme-dls/normalize.less
- packages/veui-theme-dls/package-lock.json
- packages/veui-theme-dls/package.json
- packages/veui/demo/cases/index.js
- 升级 `less-plugin-dls`
- 修改 `variables`，使得项目可以跑起来
> refactor:update to d20 style & modify variables for Form demo

- packages/veui/demo/cases/Toast.vue
- packages/veui/src/components/ToastList.vue
- packages/veui/src/managers/toast.js
> feat: provide close function for toasts

- packages/veui/src/components/Alert.vue
> fix: Correct localIndex of Alert when messages change

- packages/veui-theme-dls/components/checkbox-group.less
- packages/veui/demo/cases/CheckButtonGroup.vue
- packages/veui/demo/cases/CheckboxGroup.vue
- packages/veui/src/components/CheckButtonGroup.vue
- packages/veui/src/components/CheckboxGroup.vue
- packages/veui/test/unit/specs/components/CheckButtonGroup.spec.js
- packages/veui/test/unit/specs/components/CheckboxGroup.spec.js
> feat: check-button-group supports empty value

- packages/veui-theme-dls/components/progress.less
> fix: escape zero-width space character in CSS of Progress

- CHANGELOG.md
- packages/veui/src/components/Autocomplete/_AutocompleteBase.vue
- packages/veui/src/components/DatePicker.vue
- packages/veui/src/components/Dropdown.vue
- packages/veui/src/components/SearchBox.vue
- packages/veui/src/components/Select/Option.vue
- packages/veui/src/components/Select/Select.vue
- packages/veui/src/components/TimePicker/TimePicker.vue
- packages/veui/src/mixins/controllable.js
- packages/veui/src/mixins/dropdown.js
- packages/veui/src/mixins/key-select.js
- packages/veui/src/mixins/searchable.js
- packages/veui/test/unit/specs/components/Dropdown.spec.js
- packages/veui/test/unit/specs/components/Select/OptionGroup.spec.js
Affected components:
- Dropdown
- Select
- Autocomplete
- SearchBox
- DatePicker
- TimePicker
> feat: add `expanded` prop to components with dropdowns

- packages/veui/test/unit/specs/components/Uploader.spec.js
> New uploader

- packages/veui/src/components/Pagination.vue
fix Pagination goto button not responding
> fix Pagination goto button not responding

- packages/veui/src/components/Lightbox.vue
- packages/veui/src/components/Uploader.vue
- packages/veui/test/unit/specs/components/Lightbox.spec.js
- packages/veui/test/unit/specs/components/Uploader.spec.js
1. 添加Lightbox单元测试
2. 更新Uploader单元测试，增加新功能测试
3. fix control 下拉框点击事件缺少参数
> feat: add Lightbox unit test and update Uploader unit test

- packages/veui/demo/cases/Table.vue
- packages/veui/src/components/Table/Column.vue
- packages/veui/src/components/Table/_TableHead.js
- packages/veui/src/components/Tooltip.vue
- packages/veui/src/utils/dom.js
- packages/veui/test/unit/specs/components/Table.spec.js
it add prop of desc for column, that support popover at head of table component
Referenc: #748
> feat: add popover to head of table component

- packages/veui/src/components/Table/_TableHead.js
- packages/veui/src/utils/dom.js
- add isFocusableWithSelector function
> fix: table desc popover show except focusable element

- packages/veui-theme-dls/components/tooltip.less
> fix: add break-word for Tooltip

- packages/veui/src/components/Uploader.vue
- packages/veui/test/unit/specs/components/Uploader.spec.js
> fix: fix Uploader extensions prop is invalid

- packages/veui/src/components/Uploader.vue
- packages/veui/test/unit/specs/components/Uploader.spec.js
fix: Uploader scopedSlots添加status
> fix: fix Uploader scopedSlots

- packages/veui-theme-dls/components/Table.js
- packages/veui-theme-dls/components/button.less
- packages/veui-theme-dls/components/table.less
- packages/veui-theme-dls/package-lock.json
- packages/veui-theme-dls/package.json
- packages/veui/demo/cases/Table.vue
- packages/veui/src/components/Accordion.vue
- packages/veui/src/components/Table/Column.vue
- packages/veui/src/components/Table/_Sorter.vue
- packages/veui/src/components/Table/_TableFoot.js
- packages/veui/src/components/Table/_TableHead.js
- packages/veui/src/components/Table/_TableRow.js
- packages/veui/src/components/Tabs/Tabs.vue
- packages/veui/src/mixins/colgroup.js
- packages/veui/src/mixins/coupled.js
- packages/veui/src/utils/helper.js
- packages/veui/test/unit/specs/components/Table.spec.js
- vercel.json
... and refactor table to use the `coupled` mixin.
> Support filter for table

- packages/veui/src/components/Uploader.vue
fix: 修复iframe模式下Uploader设置max-size无效的问题
> fix: fix Uploader iframe mode max-size prop is invalidate

- packages/veui/demo/cases/Plugins.vue
- packages/veui/demo/cases/index.js
- packages/veui/src/managers/confirm.js
> $confirm 在 ok/cancel 为同步时不需要显示 loading 状态

- packages/veui-theme-dls/components/switch.less
> fix: switch component disabled style on hover state

- packages/veui/src/components/SearchBox.vue
- packages/veui/src/mixins/controllable.js
- packages/veui/test/unit/specs/components/Checkbox.spec.js
- packages/veui/test/unit/specs/components/SearchBox.spec.js
> fix: emit search event when Enter is pressed for SearchBox (#806)

- packages/veui/karma.conf.js
- packages/veui/src/components/Dialog.vue
- packages/veui/test/unit/specs/components/Dialog.spec.js
> feat: add `disabled` prop for Dialog to control ok button

- CHANGELOG.md
- packages/veui-theme-dls/components/carousel.less
- packages/veui/src/components/Carousel.vue
...and enlarge click area of progress indicators.
Fixes #811.
> fix(style): make carousel respond to container size change

- CHANGELOG.md
- packages/veui/demo/cases/AlertBox.vue
- packages/veui/src/components/AlertBox.vue
- packages/veui/src/components/ConfirmBox.vue
- packages/veui/src/components/Dialog.vue
- packages/veui/src/components/Drawer.vue
- packages/veui/src/components/Overlay.vue
- packages/veui/src/components/PromptBox.vue
- packages/veui/src/components/Tabs/Tabs.vue
- packages/veui/src/components/Transfer/Transfer.vue
- packages/veui/src/components/Transfer/_CandidatePanel.vue
- packages/veui/src/components/Transfer/_SelectedPanel.vue
- packages/veui/test/unit/specs/components/AlertBox.spec.js
- packages/veui/test/unit/specs/components/ConfirmBox.spec.js
- packages/veui/test/unit/specs/components/Dialog.spec.js
- packages/veui/test/unit/specs/components/Drawer.spec.js
- packages/veui/test/unit/specs/components/PromptBox.spec.js
> feat: add customizable labels/titles for multiple components

- packages/veui/src/components/Uploader/_FileUploader.vue
- packages/veui/src/components/Uploader/_MediaUploader.vue
> fix: fix transitions not working for uploader file list (#859)

- packages/veui/demo/cases/Input.vue
- packages/veui/src/components/Input.vue
- packages/veui/test/unit/specs/components/Input.spec.js
Resolves #874.
```ts
type TrimProp = boolean | 'start' | 'end' | 'both'
```
> feat: add `trim` prop for Input

- packages/veui/demo/cases/Textarea.vue
- packages/veui/src/components/Textarea.vue
- packages/veui/src/utils/dom.js
- packages/veui/test/global.js
- packages/veui/test/unit/specs/components/Textarea.spec.js
> fix: make textarea aware of container resize

- packages/veui/src/components/Input.vue
- packages/veui/test/unit/specs/components/Input.spec.js
Fixes https://github.com/ecomfe/veui/issues/874#issuecomment-904423288
> Only trim input value on `change` instead of `input`

- packages/veui/src/components/Collapse.vue
- packages/veui/test/unit/specs/components/Accordion.spec.js
- packages/veui/test/unit/specs/components/AlertBox.spec.js
- packages/veui/test/unit/specs/components/ConfirmBox.spec.js
- packages/veui/test/unit/specs/components/PromptBox.spec.js
… if they do not have their own.
> fix: collapse should use `toggle-position` from accordions

- package-lock.json
- packages/babel-plugin-veui/package-lock.json
- packages/veui-loader/package-lock.json
- packages/veui-theme-dls-icons/package-lock.json
- packages/veui-theme-dls/package-lock.json
- packages/veui/package-lock.json
- packages/veui/src/components/Overlay.vue
- packages/veui/test/unit/specs/components/Overlay.spec.js
> fix: only focus after overlay is opened completely

- packages/veui-theme-dls/components/search-box.less
- packages/veui/demo/cases/SearchBox.vue
- packages/veui/src/components/SearchBox.vue
- packages/veui/types/components/search-box.d.ts
Props added:
- `maxlength`
- `getLength`
- `strict`
- `trim`
> feat: enable more input props for search-box

- packages/veui-theme-dls/components/drawer.less
- packages/veui/demo/cases/Drawer.vue
- packages/veui/src/components/Dialog.vue
- packages/veui/src/components/Drawer.vue
- packages/veui/src/components/Overlay.vue
- packages/veui/src/components/Schedule.vue
- packages/veui/src/managers/focus.js
- packages/veui/src/mixins/overlay.js
- packages/veui/src/utils/dom.js
- packages/veui/src/utils/helper.js
- packages/veui/test/unit/specs/components/Drawer.spec.js
- packages/veui/test/unit/specs/components/Dropdown.spec.js
- packages/veui/test/unit/specs/utils/helper.spec.js
* add support for Drawer indent
* simplify focus trap implementation (removed ward elements)
* add `preventScroll: true` for focus helpers
* improve class/style binding normalizers
> feat: support drawer indent, improve class/style normalization

- CHANGELOG.md
- packages/veui-theme-dls/components/slider.less
- packages/veui/src/components/Slider.vue
- packages/veui/src/directives/nudge.js
- packages/veui/test/unit/specs/components/Slider.spec.js
...and improve tooltip hide timing.
> feat: support both x and y directions for slider nudge

- packages/veui/demo/cases/Tabs.vue
- packages/veui/src/components/Tabs/Tab.vue
- packages/veui/src/components/Tabs/Tabs.vue
- packages/veui/test/unit/specs/components/Table.spec.js
- packages/veui/test/unit/specs/components/Tabs.spec.js
- packages/veui/types/components/tab.d.ts
> feat: add tooltip for truncated tab label

- packages/veui-theme-dls/components/input.less
- packages/veui-theme-dls/components/tree.less
- packages/veui/demo/cases/Select.vue
- packages/veui/src/components/Input.vue
- packages/veui/src/components/Select/OptionGroup.vue
- packages/veui/src/components/Tag.vue
* improve autofill implementation
* align select popup options better
* remove button in tags should receive focus
> refactor: some minor refinements

- packages/veui/demo/cases/RadioButtonGroup.vue
- packages/veui/src/components/RadioButtonGroup.vue
- packages/veui/test/unit/specs/components/RadioButtonGroup.spec.js
- packages/veui/test/unit/specs/components/RadioGroup.spec.js
Fixes #1086 
Added some test cases.
> fix: keyboard access should honor `disabled` for RadioButtonGroup

- packages/veui-theme-dls/components/table.less
- packages/veui/demo/cases/Table.vue
- packages/veui/src/components/Table/Table.vue
- packages/veui/test/unit/specs/components/Table.spec.js
...even `scroll` prop is not set.
> fix: table head should always scroll with its body

- packages/veui/demo/cases/Select.vue
- packages/veui/src/components/Select/Select.vue
- packages/veui/src/components/_SelectTrigger.vue
- packages/veui/test/unit/specs/components/Select/Select.spec.js
…and prevent keyboard behavior for non-editable select.
> fix: make readonly select tags more readable

- packages/veui-theme-dls/components/table.less
- packages/veui/src/components/Table/Table.vue
- packages/veui/src/components/Table/_ColGroup.js
- packages/veui/src/components/Table/_Foot.js
- packages/veui/src/components/Table/_Head.js
- packages/veui/test/unit/specs/components/Table.spec.js
> feat: add sticky scrollbar for table

- packages/veui/src/components/Input.vue
- packages/veui/src/components/NumberInput.vue
> fix: fix composition makes spinners stop working for number input

- packages/veui/src/components/Table/Table.vue
- packages/veui/test/unit/specs/components/Table.spec.js
table component support function columnFilter
> feat: table component support function columnFilter

- .stylelintrc
- packages/veui-theme-dls/components/cascader.less
- packages/veui-theme-dls/components/select.less
- packages/veui-theme-dls/trigger.less
- packages/veui/demo/cases/Cascader.vue
- packages/veui/demo/cases/Select.vue
- packages/veui/src/components/_SelectTrigger.vue
> fix: improve styles for select/cascader with custom #selected slot

- packages/veui/demo/cases/DatePicker.vue
- packages/veui/demo/cases/NumberInput.vue
- packages/veui/demo/cases/Select.vue
- packages/veui/src/components/DatePicker.vue
- packages/veui/src/components/NumberInput.vue
- packages/veui/src/components/Select/Select.vue
feat: add before slot for Select & DatePicker
> feat: add before slot for Select & DatePicker
